const { contextBridge, ipcRenderer } = require('electron');
const { createEmptyAgentRuntimeState } = require('./lib/agent-runtime');

contextBridge.exposeInMainWorld('xbrowser', {
    bootstrap: () => ipcRenderer.invoke('app:bootstrap'),
    getEmptyAgentRuntimeState: () => createEmptyAgentRuntimeState(),
    openAgentWindow: () => ipcRenderer.invoke('agent:window:open'),
    generateFingerprint: (payload) => ipcRenderer.invoke('fingerprint:generate', payload),
    saveProfile: (payload) => ipcRenderer.invoke('profile:save', payload),
    deleteProfile: (id) => ipcRenderer.invoke('profile:delete', id),
    clearProfileCache: (id) => ipcRenderer.invoke('profile:clear-cache', id),
    launchProfile: (id, requestId = '') => ipcRenderer.invoke('profile:launch', { id, requestId }),
    stopProfile: (id) => ipcRenderer.invoke('profile:stop', id),
    addManualProxy: (payload) => ipcRenderer.invoke('proxy:add-manual', payload),
    deleteProxy: (id) => ipcRenderer.invoke('proxy:delete', id),
    testProxy: (id) => ipcRenderer.invoke('proxy:test', id),
    importSubscription: (payload) => ipcRenderer.invoke('subscription:import', payload),
    refreshSubscription: (id) => ipcRenderer.invoke('subscription:refresh', id),
    deleteSubscription: (id) => ipcRenderer.invoke('subscription:delete', id),
    importProxyFile: () => ipcRenderer.invoke('proxy:import-file'),
    saveAgentProvider: (payload) => ipcRenderer.invoke('agent:provider:save', payload),
    deleteAgentProvider: (id) => ipcRenderer.invoke('agent:provider:delete', id),
    setActiveAgentProvider: (id) => ipcRenderer.invoke('agent:provider:set-active', id),
    fetchAgentModels: (payload) => ipcRenderer.invoke('agent:provider:fetch-models', payload),
    stopAgentTask: () => ipcRenderer.invoke('agent:stop'),
    startAgentSession: (payload) => ipcRenderer.invoke('agent:session:start', payload),
    sendAgentSessionMessage: (payload) => ipcRenderer.invoke('agent:session:send', payload),
    startAgentBatch: (payload) => ipcRenderer.invoke('agent:batch:start', payload),
    clearAgentState: () => ipcRenderer.invoke('agent:clear'),
    saveSettings: (payload) => ipcRenderer.invoke('settings:save', payload),
    openDataDir: () => ipcRenderer.invoke('app:open-data-dir'),
    onStateUpdated: (callback) => ipcRenderer.on('state-updated', (event, state) => callback(state)),
    onLaunchProgress: (callback) => ipcRenderer.on('launch-progress', (event, payload) => callback(payload)),
    onAgentEvent: (callback) => ipcRenderer.on('agent-event', (event, payload) => callback(payload))
});
