const { contextBridge, ipcRenderer } = require('electron');
const { createEmptyAgentRuntimeState } = require('./lib/agent-runtime');

contextBridge.exposeInMainWorld('xbrowser', {
    bootstrap: () => ipcRenderer.invoke('app:bootstrap'),
    getEmptyAgentRuntimeState: () => createEmptyAgentRuntimeState(),
    openAgentWindow: () => ipcRenderer.invoke('agent:window:open'),
    generateFingerprint: (payload) => ipcRenderer.invoke('fingerprint:generate', payload),
    saveProfile: (payload) => ipcRenderer.invoke('profile:save', payload),
    cloneProfile: (id) => ipcRenderer.invoke('profile:clone', id),
    batchCreateProfiles: (payload) => ipcRenderer.invoke('profile:batch-create', payload),
    exportProfiles: (payload) => ipcRenderer.invoke('profile:export', payload),
    importProfiles: () => ipcRenderer.invoke('profile:import'),
    deleteProfile: (id) => ipcRenderer.invoke('profile:delete', id),
    trashProfile: (id) => ipcRenderer.invoke('profile:trash', id),
    restoreProfile: (id) => ipcRenderer.invoke('profile:restore', id),
    destroyProfile: (id) => ipcRenderer.invoke('profile:destroy', id),
    moveProfilesToProject: (payload) => ipcRenderer.invoke('profile:move-to-project', payload),
    clearProfileCache: (id) => ipcRenderer.invoke('profile:clear-cache', id),
    launchProfile: (id, requestId = '') => ipcRenderer.invoke('profile:launch', { id, requestId }),
    stopProfile: (id) => ipcRenderer.invoke('profile:stop', id),
    listTemplates: () => ipcRenderer.invoke('template:list'),
    saveTemplate: (payload) => ipcRenderer.invoke('template:save', payload),
    deleteTemplate: (id) => ipcRenderer.invoke('template:delete', id),
    createProject: (payload) => ipcRenderer.invoke('project:create', payload),
    updateProject: (payload) => ipcRenderer.invoke('project:update', payload),
    deleteProject: (id) => ipcRenderer.invoke('project:delete', id),
    listExtensions: () => ipcRenderer.invoke('extension:list'),
    importUnpackedExtension: () => ipcRenderer.invoke('extension:import-unpacked'),
    importCrxExtension: () => ipcRenderer.invoke('extension:import-crx'),
    toggleExtension: (payload) => ipcRenderer.invoke('extension:toggle', payload),
    batchAssignExtension: (payload) => ipcRenderer.invoke('extension:batch-assign', payload),
    deleteExtension: (id) => ipcRenderer.invoke('extension:delete', id),
    listAccounts: () => ipcRenderer.invoke('account:list'),
    createAccount: (payload) => ipcRenderer.invoke('account:create', payload),
    updateAccount: (payload) => ipcRenderer.invoke('account:update', payload),
    deleteAccount: (id) => ipcRenderer.invoke('account:delete', id),
    bindAccountProfile: (payload) => ipcRenderer.invoke('account:bind-profile', payload),
    importAccountCookies: (payload) => ipcRenderer.invoke('account:import-cookies', payload),
    exportAccountCookies: (payload) => ipcRenderer.invoke('account:export-cookies', payload),
    importAccountStorage: (payload) => ipcRenderer.invoke('account:import-storage', payload),
    exportAccountStorage: (payload) => ipcRenderer.invoke('account:export-storage', payload),
    addManualProxy: (payload) => ipcRenderer.invoke('proxy:add-manual', payload),
    batchAssignProxy: (payload) => ipcRenderer.invoke('proxy:batch-assign', payload),
    refreshProxyGeo: (payload) => ipcRenderer.invoke('proxy:refresh-geo', payload),
    allocateProxy: (payload) => ipcRenderer.invoke('proxy:allocate', payload),
    deleteProxy: (id) => ipcRenderer.invoke('proxy:delete', id),
    testProxy: (id) => ipcRenderer.invoke('proxy:test', id),
    importSubscription: (payload) => ipcRenderer.invoke('subscription:import', payload),
    refreshSubscription: (id) => ipcRenderer.invoke('subscription:refresh', id),
    deleteSubscription: (id) => ipcRenderer.invoke('subscription:delete', id),
    importProxyFile: () => ipcRenderer.invoke('proxy:import-file'),
    saveAgentProvider: (payload) => ipcRenderer.invoke('agent:provider:save', payload),
    deleteAgentProvider: (id) => ipcRenderer.invoke('agent:provider:delete', id),
    setActiveAgentProvider: (id) => ipcRenderer.invoke('agent:provider:set-active', id),
    fetchAgentModels: (payload) => ipcRenderer.invoke('agent:provider:fetch-models', payload),
    stopAgentTask: () => ipcRenderer.invoke('agent:stop'),
    startAgentSession: (payload) => ipcRenderer.invoke('agent:session:start', payload),
    sendAgentSessionMessage: (payload) => ipcRenderer.invoke('agent:session:send', payload),
    startAgentBatch: (payload) => ipcRenderer.invoke('agent:batch:start', payload),
    exportAgentBatchResults: () => ipcRenderer.invoke('agent:batch:export'),
    startSyncSession: (payload) => ipcRenderer.invoke('sync:start', payload),
    stopSyncSession: () => ipcRenderer.invoke('sync:stop'),
    getSyncState: () => ipcRenderer.invoke('sync:get-state'),
    clearAgentState: () => ipcRenderer.invoke('agent:clear'),
    saveSettings: (payload) => ipcRenderer.invoke('settings:save', payload),
    openDataDir: () => ipcRenderer.invoke('app:open-data-dir'),
    onStateUpdated: (callback) => ipcRenderer.on('state-updated', (event, state) => callback(state)),
    onLaunchProgress: (callback) => ipcRenderer.on('launch-progress', (event, payload) => callback(payload)),
    onAgentEvent: (callback) => ipcRenderer.on('agent-event', (event, payload) => callback(payload))
});
